version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  disable-all: true
  enable:
    - staticcheck
    - govet
    - errcheck
    - ineffassign
    - unused
  settings:
    govet:
      enable-all: true

linters-settings:
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck
          - ineffassign
          - unused
    paths:
      - navidrome_data

formatters:
  enable:
    - goimports
    - gofmt
  settings:
    goimports:
      local-prefixes: github.com/cesargomez89/navidrums
    gofmt:
      simplify: true
