version: 2

project_name: navidrums

archives:
  - format: binary
    builds:
      - navidrums
    files:
      - none::*

checksum:
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}-snapshot-{{ .ShortCommit }}"

release:
  github:
    owner: cesargomez89
    name: navidrums
  draft: true
  prerelease: auto

builds:
  - id: navidrums
    main: ./cmd/server
    binary: navidrums
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

