package musicbrainz

// DefaultGenreMap maps raw MusicBrainz tag names (lowercase) to canonical genre labels.
// The map is used by extractMainGenre to normalize genre data from the API.
var DefaultGenreMap = map[string]string{
	"rock":                "rock",
	"alternative rock":    "rock",
	"indie rock":          "rock",
	"hard rock":           "rock",
	"punk":                "rock",
	"punk rock":           "rock",
	"post-punk":           "rock",
	"garage rock":         "rock",
	"grunge":              "rock",
	"emo":                 "rock",
	"soft rock":           "rock",
	"industrial rock":     "rock",
	"metal":               "metal",
	"heavy metal":         "metal",
	"nu metal":            "metal",
	"death metal":         "metal",
	"black metal":         "metal",
	"thrash metal":        "metal",
	"metalcore":           "metal",
	"progressive metal":   "metal",
	"rap metal":           "metal",
	"alternative metal":   "metal",
	"industrial metal":    "metal",
	"neue deutsche härte": "metal",
	"funk metal":          "metal",
	"pop":                 "pop",
	"indie pop":           "pop",
	"synthpop":            "pop",
	"dance pop":           "pop",
	"electropop":          "pop",
	"latin pop":           "pop",
	"art pop":             "pop",
	"noise pop":           "pop",
	"synth-pop":           "pop",
	"dance-pop":           "pop",
	"hip hop":             "hip-hop",
	"rap":                 "hip-hop",
	"trap":                "hip-hop",
	"drill":               "hip-hop",
	"boom bap":            "hip-hop",
	"latin trap":          "hip-hop",
	"abstract hip hop":    "hip-hop",
	"hardcore rap":        "hip-hop",
	"hip-hop/rap":         "hip-hop",
	"rap/hip hop":         "hip-hop",
	"melodic rap":         "hip-hop",
	"r&b":                 "r&b",
	"rnb":                 "r&b",
	"contemporary r&b":    "r&b",
	"soul":                "r&b",
	"neo soul":            "r&b",
	"funk":                "r&b",
	"rhythm and blues":    "r&b",
	"electronic":          "electronic",
	"edm":                 "electronic",
	"house":               "electronic",
	"techno":              "electronic",
	"trance":              "electronic",
	"dubstep":             "electronic",
	"drum and bass":       "electronic",
	"dnb":                 "electronic",
	"trip hop":            "electronic",
	"alternative dance":   "electronic",
	"chillwave":           "electronic",
	"industrial":          "electronic",
	"club/dance":          "electronic",
	"disco":               "electronic",
	"folktronica":         "electronic",
	"microhouse":          "electronic",
	"ambient house":       "electronic",
	"electronica":         "electronic",
	"dub":                 "electronic",
	"latin":               "latin",
	"reggaeton":           "latin",
	"dembow":              "latin",
	"salsa":               "latin",
	"bachata":             "latin",
	"merengue":            "latin",
	"cumbia":              "latin",
	"bomba":               "latin",
	"bossa nova":          "latin",
	"regional mexican":    "regional mexican",
	"banda":               "regional mexican",
	"norteño":             "regional mexican",
	"norteno":             "regional mexican",
	"corridos":            "regional mexican",
	"corridos tumbados":   "regional mexican",
	"mariachi":            "regional mexican",
	"grupero":             "regional mexican",
	"sierreño":            "regional mexican",
	"sierreño urbano":     "regional mexican",
	"country":             "country",
	"americana":           "country",
	"alt-country":         "country",
	"jazz":                "jazz",
	"smooth jazz":         "jazz",
	"bebop":               "jazz",
	"classical":           "classical",
	"opera":               "classical",
	"baroque":             "classical",
	"romantic":            "classical",
	"orchestral":          "classical",
	"classical crossover": "classical",
	"folk":                "folk",
	"indie folk":          "folk",
	"acoustic":            "folk",
	"reggae":              "reggae",
	"dancehall":           "reggae",
	"ska":                 "reggae",
	"blues":               "blues",
	"soundtrack":          "soundtrack",
	"film score":          "soundtrack",
}
