package musicbrainz

// DefaultGenreMap maps raw MusicBrainz tag names (lowercase) to canonical genre labels.
// The map is used by extractMainGenre to normalize genre data from the API.
var DefaultGenreMap = map[string]string{
	"rock":                "Rock",
	"alternative rock":    "Rock",
	"indie rock":          "Rock",
	"hard rock":           "Rock",
	"punk":                "Rock",
	"punk rock":           "Rock",
	"post-punk":           "Rock",
	"garage rock":         "Rock",
	"grunge":              "Rock",
	"emo":                 "Rock",
	"soft rock":           "Rock",
	"industrial rock":     "Rock",
	"metal":               "Metal",
	"heavy metal":         "Metal",
	"nu metal":            "Metal",
	"death metal":         "Metal",
	"black metal":         "Metal",
	"thrash metal":        "Metal",
	"metalcore":           "Metal",
	"progressive metal":   "Metal",
	"rap metal":           "Metal",
	"alternative metal":   "Metal",
	"industrial metal":    "Metal",
	"neue deutsche härte": "Metal",
	"funk metal":          "Metal",
	"pop":                 "Pop",
	"indie pop":           "Pop",
	"synthpop":            "Pop",
	"dance pop":           "Pop",
	"electropop":          "Pop",
	"latin pop":           "Pop",
	"art pop":             "Pop",
	"noise pop":           "Pop",
	"synth-pop":           "Pop",
	"dance-pop":           "Pop",
	"hip hop":             "Hip-Hop",
	"rap":                 "Hip-Hop",
	"trap":                "Hip-Hop",
	"drill":               "Hip-Hop",
	"boom bap":            "Hip-Hop",
	"latin trap":          "Hip-Hop",
	"abstract hip hop":    "Hip-Hop",
	"hardcore rap":        "Hip-Hop",
	"hip-hop/rap":         "Hip-Hop",
	"rap/hip hop":         "Hip-Hop",
	"melodic rap":         "Hip-Hop",
	"r&b":                 "R&B",
	"rnb":                 "R&B",
	"contemporary r&b":    "R&B",
	"soul":                "R&B",
	"neo soul":            "R&B",
	"funk":                "R&B",
	"rhythm and blues":    "R&B",
	"electronic":          "Electronic",
	"edm":                 "Electronic",
	"house":               "Electronic",
	"techno":              "Electronic",
	"trance":              "Electronic",
	"dubstep":             "Electronic",
	"drum and bass":       "Electronic",
	"dnb":                 "Electronic",
	"trip hop":            "Electronic",
	"alternative dance":   "Electronic",
	"chillwave":           "Electronic",
	"industrial":          "Electronic",
	"club/dance":          "Electronic",
	"disco":               "Electronic",
	"folktronica":         "Electronic",
	"microhouse":          "Electronic",
	"ambient house":       "Electronic",
	"electronica":         "Electronic",
	"dub":                 "Electronic",
	"latin":               "Latin",
	"reggaeton":           "Latin",
	"dembow":              "Latin",
	"salsa":               "Latin",
	"bachata":             "Latin",
	"merengue":            "Latin",
	"cumbia":              "Latin",
	"bomba":               "Latin",
	"bossa nova":          "Latin",
	"regional mexican":    "Regional Mexican",
	"banda":               "Regional Mexican",
	"norteño":             "Regional Mexican",
	"norteno":             "Regional Mexican",
	"corridos":            "Regional Mexican",
	"corridos tumbados":   "Regional Mexican",
	"mariachi":            "Regional Mexican",
	"grupero":             "Regional Mexican",
	"sierreño":            "Regional Mexican",
	"sierreño urbano":     "Regional Mexican",
	"country":             "Country",
	"americana":           "Country",
	"alt-country":         "Country",
	"jazz":                "Jazz",
	"smooth jazz":         "Jazz",
	"bebop":               "Jazz",
	"classical":           "Classical",
	"opera":               "Classical",
	"baroque":             "Classical",
	"romantic":            "Classical",
	"orchestral":          "Classical",
	"classical crossover": "Classical",
	"folk":                "Folk",
	"indie folk":          "Folk",
	"acoustic":            "Folk",
	"reggae":              "Reggae",
	"dancehall":           "Reggae",
	"ska":                 "Reggae",
	"blues":               "Blues",
	"soundtrack":          "Soundtrack",
	"film score":          "Soundtrack",
}
